### ISSUE TITLE
I created pull request for new feature.

### ISSUE THREAD

**Issue by lapinskik** [dhanasingh/redmine_wktime#159]
Hello, I created pull request for ERPmine custom fields.
My company were really missing a way to assign ERPmine CRM accounts, contacts and leads to Redmine Issues so I made a new field format that makes now possible to add new types of custom fields. Now you can add custom field of type "crm contacts, crm lead, crm account" and assign it to Redmine Document/Issue/Project/Version. But it's not everything, you can also go to settings in ERPmine and create ERPcustom field that would render related Issues/Document/Project/Version inside CRM account/lead/contact.
I would be very glad if you would test it out, and if you'd like to merge it to project.
Thanks in advance.

**Comment by dhanasingh** [comment]
yeah we saw that, nice work.
I think it is little tricky.
We are already attaching an account/contact to a project through billable projects.
Once attached, that can be used as "Spent for" in the spent time page, basically you can say which account / contact you are putting this time in a project.

now you are trying to attach Accounts / Contacts / Leads to an Issue, that might be little confusing because we already attaching that to a project.

Thats why we are not sure how to take in your changes

**Comment by r0d0dendr0n** [comment]
What about a case where you're running a single project for a team of customer support workers and they are resolving tickets (issues) for different customers (Accounts / Contacts / Leads)? Let's say that all the issues are related to a single product, thus a single project is justified. I think that it would be nice to provide a way to assign customer entities directly to issues and be able to check how much work is generated by selected customers. It would be nice to see that even across different projects.

Could you provide some instructions on how to assign an Account or a Contact to a project? I don't think I understand what are billable projects.

Nice to hear from you guys! Kind regards from Poland.

**Comment by dhanasingh** [comment]
To setup billable projects:
1) enable billing module in plugin configuration
2) then go to Erpmine -> Billing -> Billable Projects
Add billable projects, you can attach any number of accounts / contacts to a project
3) Go to Log time or Erpmine Timesheet, you will see a dropdown of account / contacts in the "Spent For" dropdown

Right now, we can assign account / contacts to spent time, we can figure out a way to attach to an issue

**Comment by r0d0dendr0n** [comment]
I guess that this feature is nice when developing project features (subprojects) for a specific customer. Pretty cool that it's possible to bill an Account or Client for work done. Do you plan on billing different customers in scope of one project?

Also I'm trying to figure out if linking Accounts / Contacts via Billable Project collides in any way with linking issues or documents to them. I think that these methods could coexist and serve different purposes.

**Comment by dhanasingh** [comment]
Billing different customers from a single project is already there, you have to create billable project for each customer for the same project.
We can try and put a dropdown of accounts / contacts on the issue page for selection (in one of the future release )
Regarding documents, won't you want to attach a document to an account / contact instead of other way around, then we want to have 'add document' button on the account / contact page right ?

**Comment by dhanasingh** [comment]
Happy New Year to you too !!
Yes we can get on a call, can you send an email to info@adhisoftware.co.in, then we will take it from there ?
