### ISSUE TITLE
Custom field ID Conflict in wktime

### ISSUE THREAD

**Issue by PascalP333** [dhanasingh/redmine_wktime#205]
I use version 3.9.3 and Redmine 4.1.1 on Linux
With the following scenario : 
- Custom field in Spent Time :
-- Custom field ID 3 and 32

When I reach 20 row in the week time sheet, the ID regerated from the template in the javascript (__template__)  get wrong custom field ID because of this code in the assets/javascripts/edit.js (function renameIDName ). The regex replace will change the first field id to _custom_field_value_320_ which is exactly the same name at the template one ( custom field id 32 (320). So in the process, both IDs  are replaced and this lead to a post with _custom_field_value_3 having no values and the ID 32 with 14 values.

This lead to this server error : 
Completed 500 Internal Server Error in 196ms (ActiveRecord: 37.2ms)

NoMethodError (undefined method `[]' for nil:NilClass):

plugins/redmine_wktime/app/controllers/wktime_controller.rb:1445:in `block (3 levels) in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1434:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1434:in `block (2 levels) in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1395:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1395:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1395:in `block in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1380:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1380:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1380:in `gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:176:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

If I change the ID of the first field (3) directly in the database, everything is working fine.

If you need more informations, don't hesitate to ask !

**Comment by PascalP333** [comment]
Here's the generated ID taken from the inspect in the web browser : 
Line 19
![image](https://user-images.githubusercontent.com/66318833/83534014-4cf3a980-a4be-11ea-9bb0-e9034665f6d1.png)
Line 20
![image](https://user-images.githubusercontent.com/66318833/83533760-fab28880-a4bd-11ea-8689-b840b70ec8b3.png)

**Comment by PascalP333** [comment]
Hello, is there a plan to fix this ?

Thank you

**Comment by amutha1997** [comment]
This will be fixed in 4.0 which will probably be released next week.

**Comment by PascalP333** [comment]
Thank you for this follow up ! Glad to have it fixed !

Good work !

**Comment by amutha1997** [comment]
4.0 is released, Please take a look.

**Comment by consensusdevteam** [comment]
Hi! I see that this issue was solved in v4.0. But in v4.0.1 redmine crashes in the spend time field after reaching the 20 row in the week time. 

Tested in Redmine 4.1.1 + wk_time 4.0.1 

Completed 404 Not Found in 71ms (ActiveRecord: 7.8ms)

ActiveRecord::RecordNotFound (Couldn't find WkSpentFor with ID=1312 for TimeEntry with ID=):

plugins/redmine_wktime/app/controllers/wktime_controller.rb:1435:in `block (2 levels) in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1427:in `block in gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `each'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `each_with_index'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:1411:in `gatherEntries'
plugins/redmine_wktime/app/controllers/wktime_controller.rb:183:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by amutha1997** [comment]
This issue is fixed in 4.0.2 . 4.0.2 is released, Please take a look.
